'use client';
import {useState,useEffect,useRef,useCallback} from 'react';
import {Dumbbell,ArrowUpRight,Play,Pause,RotateCcw,MoveUpRight,ChevronRight,Check,Minus,Plus,Scan,Info} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
import {Field} from '@base-ui/react/field';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import AnatomyScene,{View} from './scene';
import {exercises,groups} from './exercises';
export default function Home(){
 const [id,setId]=useState('curl'),[group,setGroup]=useState('Biceps'),[goal,setGoal]=useState('build'),[reps,setReps]=useState(12),[speed,setSpeed]=useState(1),[playing,setPlaying]=useState(false),[progress,setProgress]=useState(0),[ready,setReady]=useState(false),[view,setView]=useState<View>('front'),[reset,setReset]=useState(0);
 const progressRef=useRef(0),playingRef=useRef(false);const exercise=exercises.find(e=>e.id===id)!;const complete=progress>=reps;const currentRep=Math.min(reps,Math.floor(progress)+1);const fraction=complete?0:progress%1;const phaseIndex=fraction<.5?0:1;
 const choose=useCallback((exerciseId:string)=>{const e=exercises.find(x=>x.id===exerciseId);if(!e)return;setId(e.id);setGroup(e.group);setView(e.view);setPlaying(false);playingRef.current=false;setProgress(0);progressRef.current=0;},[]);
 const seek=useCallback((value:number)=>{progressRef.current=value;setProgress(value);},[]);
 const clear=()=>{setPlaying(false);playingRef.current=false;seek(0);};
 useEffect(()=>{playingRef.current=playing;},[playing]);
 useEffect(()=>{if(!playing)return;let raf=0,last=0;const tick=(now:number)=>{if(!playingRef.current)return;if(last){const delta=Math.min((now-last)/1000,.1);progressRef.current=Math.min(reps,progressRef.current+delta*speed/4);setProgress(progressRef.current);if(progressRef.current>=reps){setPlaying(false);playingRef.current=false;return;}}last=now;raf=requestAnimationFrame(tick);};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf);},[playing,reps,speed]);
 useEffect(()=>{const hidden=()=>{if(document.hidden){setPlaying(false);playingRef.current=false;}};document.addEventListener('visibilitychange',hidden);return()=>document.removeEventListener('visibilitychange',hidden);},[]);
 useEffect(()=>{
  const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
  try{Promise.resolve(context.registerTool({name:'configure_exercise',title:'Configure exercise preview',description:'Select an exercise and target reps, reset the set, and leave playback paused.',inputSchema:{type:'object',properties:{exerciseId:{type:'string',enum:exercises.map(e=>e.id)},reps:{type:'integer',minimum:1,maximum:30}},required:['exerciseId','reps'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{const v=input as any;if(!v||typeof v!=='object'||!exercises.some(e=>e.id===v.exerciseId)||!Number.isInteger(v.reps)||v.reps<1||v.reps>30)throw Error('Choose a listed exercise and 1–30 reps.');choose(v.exerciseId);setReps(v.reps);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return{exerciseId:v.exerciseId,reps:v.reps,playing:false};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();
 },[choose]);
 return <main className="studio">
  <header><a className="brand" href="/" aria-label="Muscle Atlas home"><Dumbbell/> MUSCLE<span>ATLAS</span><small> / MOTION LAB</small></a><span className="header-note"><i/> Understand every rep</span></header>
  <div className="intro"><div><p className="eyebrow">TRAIN WITH INTENTION</p><h1>See the movement.<br/><span>Feel the difference.</span></h1></div><Tabs value={goal} onValueChange={v=>setGoal(String(v))} className="goal-tabs"><TabsList aria-label="Training goal"><TabsTrigger value="build"><Dumbbell size={15}/>Build muscle</TabsTrigger><TabsTrigger value="lean"><Scan size={15}/>Lean up</TabsTrigger></TabsList><TabsContent value="build"><p>Learn the movement. Progress your resistance.</p></TabsContent><TabsContent value="lean"><p>Keep strength training part of your routine.</p></TabsContent></Tabs></div>
  <div className="workspace">
   <aside className="library"><p className="eyebrow">01 / EXERCISE LIBRARY</p><div className="library-heading"><h2>Find your movement</h2><span>11</span></div>
    <Tabs value={group} onValueChange={v=>{const e=exercises.find(x=>x.group===v);if(e)choose(e.id);}} orientation="vertical" className="muscle-tabs"><TabsList aria-label="Muscle group">{groups.map((g,i)=><TabsTrigger value={g} key={g}><span className="group-index">0{i+1}</span>{g}<ChevronRight size={15}/></TabsTrigger>)}</TabsList>{groups.map(g=><TabsContent key={g} value={g}><p className="exercise-caption">{g.toUpperCase()} EXERCISES</p>{exercises.filter(e=>e.group===g).map(e=><button aria-pressed={e.id===id} className={'exercise '+(e.id===id?'active':'')} key={e.id} onClick={()=>choose(e.id)}><span>{e.name}<small>{e.equipment}</small></span>{e.id===id?<ArrowUpRight size={17}/>:<ChevronRight size={15}/>}</button>)}</TabsContent>)}</Tabs>
    <div className="library-note"><Info size={16}/><p>Select a movement to see its<br/>muscles in action.</p></div>
   </aside>
   <section className="viewport" aria-label="3D exercise viewer"><div className="viewer-top"><span><i/> LIVE ANATOMY</span><span>3D / 360°</span></div>
    <AnatomyScene exercise={exercise} progress={progress} view={view} reset={reset} onReady={setReady}/>
    <div className="view-switch" role="group" aria-label="Camera view">{(['front','side','back'] as View[]).map(v=><button key={v} aria-pressed={view===v} onClick={()=>setView(v)} className={view===v?'selected':''}>{v}</button>)}</div>
    <div className="legend"><span><i/> Primary</span><span><i/> Assisting</span></div>
    <div className="rep-overlay"><span>{complete?'SET COMPLETE':playing?'IN MOTION':'MOVEMENT PREVIEW'}</span><strong>{String(complete?reps:currentRep).padStart(2,'0')}<small> / {String(reps).padStart(2,'0')}</small></strong><p>{complete?'Nice work. Ready when you are.':progress===0?'Press play to begin':exercise.phase[phaseIndex]}</p></div>
    <div className="viewer-bottom"><span>Drag to orbit · Pinch or scroll to zoom</span><button aria-label="Reset camera" onClick={()=>{setView('front');setReset(v=>v+1);}}><RotateCcw size={17}/></button></div>
   </section>
   <aside className="details"><p className="eyebrow">02 / MOVEMENT BREAKDOWN</p><h2>{exercise.name}</h2><p className="muted">{exercise.group} <span className="dot">·</span> {exercise.equipment}</p>
    <div className="divider"/><div className="muscle-label"><i/> PRIMARY MUSCLES</div><h3>{exercise.primary.join(' + ')}</h3><p className="muted action">{exercise.action}</p>{exercise.group==='Back'&&<p className="schematic-note">Lat surfaces are schematic additions.</p>}<p className="assist-label">ALSO WORKING</p><div className="muscle-chips">{exercise.secondary.map(m=><span key={m}>{m}</span>)}</div>
    <div className="divider"/><div className="reps-heading"><span>Target reps</span><div className="stepper"><button aria-label="Decrease reps" disabled={reps<=1} onClick={()=>{clear();setReps(v=>v-1);}}><Minus size={14}/></button><b>{reps}</b><button aria-label="Increase reps" disabled={reps>=30} onClick={()=>{clear();setReps(v=>v+1);}}><Plus size={14}/></button></div></div><Field.Root className="slider-field"><Field.Label className="sr-only">Target reps</Field.Label><Slider aria-label="Target reps" min={1} max={30} step={1} value={[reps]} onValueChange={v=>{clear();setReps(Array.isArray(v)?v[0]:v);}} className="rep-slider"/></Field.Root>
    <div className="speed-row"><span>Playback speed</span><div role="group" aria-label="Playback speed">{[.5,1,1.5].map(s=><button aria-pressed={s===speed} key={s} className={speed===s?'selected':''} onClick={()=>setSpeed(s)}>{s}×</button>)}</div></div>
    <button className="start" disabled={!ready} onClick={()=>{if(complete)seek(0);setPlaying(v=>!v);}}>{complete?<RotateCcw size={17}/>:playing?<Pause size={17}/>:<Play size={17}/>} {complete?'Replay set':playing?'Pause set':progress>0?'Resume set':'Start set'}</button>
    <div className="playback"><Field.Root className="slider-field"><Field.Label className="sr-only">Position in current rep</Field.Label><Slider aria-label="Position in current rep" min={0} max={.999} step={.001} value={[fraction]} disabled={!ready||complete} onValueChange={v=>{setPlaying(false);playingRef.current=false;seek(Math.floor(progress)+(Array.isArray(v)?v[0]:v));}}/></Field.Root><button aria-label="Reset set" onClick={clear}><RotateCcw size={15}/></button></div><p className="scrub-note">Slide to inspect a rep · {4/speed % 1 ? (4/speed).toFixed(1):4/speed}s per rep</p><p className="completion" aria-live="polite">{complete?<><Check size={14}/> {reps} reps completed</>:`${Math.floor(progress)} of ${reps} reps completed`}</p>
   </aside>
  </div>
  <section className="below"><div className="form-panel"><p className="eyebrow">MOVE WELL</p><h2>Keep these cues in mind.</h2><div className="cues">{exercise.cues.map((cue,i)=><div key={cue}><span>0{i+1}</span><p>{cue}</p></div>)}</div></div><div className="goal-panel"><span className="goal-badge">{goal==='build'?'BUILD MUSCLE':'LEAN UP'}</span><h3>{goal==='build'?'Control first. Then progress.':'Build strength as you lean up.'}</h3><p>{goal==='build'?'Use a resistance you can control through the full movement. As training becomes easier, gradually increase the challenge. The rep selector controls this demo, not a personalized program.':'Strength training helps you stay active while managing weight. Fat loss depends on overall energy balance; choosing a muscle or doing more reps does not target fat in that area.'}</p><a href={goal==='build'?'https://www.acefitness.org/resources/everyone/exercise-library/':'https://www.cdc.gov/healthy-weight-growth/physical-activity/index.html'} target="_blank" rel="noreferrer">{goal==='build'?'Explore the ACE exercise library':'Read the CDC activity guide'}<ArrowUpRight size={14}/></a></div></section>
  <details className="credits"><summary>About the anatomy & movement <Info size={14}/></summary><p>BodyParts3D adult male reference anatomy, © The Database Center for Life Science, <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>. Selected and repacked from <a href="https://github.com/ashemag/human-atlas">Human Atlas by ashemag</a>. <a href="/ATTRIBUTION.md">Full model attribution</a>.</p><p>The two lat surfaces are schematic additions because the source atlas omits them. Joint motion, muscle thickening, and highlight colors are illustrative. They are not measured activation, individualized form assessment, or validated biomechanics. Equipment is omitted to keep anatomy visible. For the pulldown, the model illustrates upper-body motion rather than the complete seated setup.</p></details>
  <footer><span>ANATOMY IN MOTION</span><span>Explore. Understand. Train.<MoveUpRight size={14}/></span></footer>
 </main>;
}
