'use client';
import {useState,useEffect,useRef,useCallback} from 'react';
import {Dumbbell,ArrowUpRight,Play,Pause,RotateCcw,ChevronRight,Check,Minus,Plus,Scan,Info,Menu,X} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
import {Field} from '@base-ui/react/field';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import AnatomyScene,{View} from './scene';
import {describeMuscle,exercises,groups} from './exercises';
export default function Home(){
 const [id,setId]=useState('curl'),[group,setGroup]=useState('Biceps'),[goal,setGoal]=useState('build'),[reps,setReps]=useState(12),[speed,setSpeed]=useState(1),[playing,setPlaying]=useState(false),[progress,setProgress]=useState(0),[ready,setReady]=useState(false),[view,setView]=useState<View>('front'),[reset,setReset]=useState(0);
 const [libraryOpen,setLibraryOpen]=useState(false),[infoOpen,setInfoOpen]=useState(false);
 const progressRef=useRef(0),playingRef=useRef(false);const exercise=exercises.find(e=>e.id===id)!;const complete=progress>=reps;const currentRep=Math.min(reps,Math.floor(progress)+1);const fraction=complete?0:progress%1;const phaseIndex=fraction<.5?0:1;
 const choose=useCallback((exerciseId:string)=>{const e=exercises.find(x=>x.id===exerciseId);if(!e)return;setId(e.id);setGroup(e.group);setView(e.view);setPlaying(false);playingRef.current=false;setProgress(0);progressRef.current=0;},[]);
 const seek=useCallback((value:number)=>{progressRef.current=value;setProgress(value);},[]);
 const clear=()=>{setPlaying(false);playingRef.current=false;seek(0);};
 useEffect(()=>{playingRef.current=playing;},[playing]);
 useEffect(()=>{if(!playing)return;let raf=0,last=0;const tick=(now:number)=>{if(!playingRef.current)return;if(last){const delta=Math.min((now-last)/1000,.1);progressRef.current=Math.min(reps,progressRef.current+delta*speed/4);setProgress(progressRef.current);if(progressRef.current>=reps){setPlaying(false);playingRef.current=false;return;}}last=now;raf=requestAnimationFrame(tick);};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf);},[playing,reps,speed]);
 useEffect(()=>{const hidden=()=>{if(document.hidden){setPlaying(false);playingRef.current=false;}};document.addEventListener('visibilitychange',hidden);return()=>document.removeEventListener('visibilitychange',hidden);},[]);
 useEffect(()=>{
  const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
  try{Promise.resolve(context.registerTool({name:'configure_exercise',title:'Configure exercise preview',description:'Select an exercise and target reps, reset the set, and leave playback paused.',inputSchema:{type:'object',properties:{exerciseId:{type:'string',enum:exercises.map(e=>e.id)},reps:{type:'integer',minimum:1,maximum:30}},required:['exerciseId','reps'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{const v=input as any;if(!v||typeof v!=='object'||!exercises.some(e=>e.id===v.exerciseId)||!Number.isInteger(v.reps)||v.reps<1||v.reps>30)throw Error('Choose a listed exercise and 1–30 reps.');choose(v.exerciseId);setReps(v.reps);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return{exerciseId:v.exerciseId,reps:v.reps,playing:false};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();
 },[choose]);
 return <main className="studio">
  <header className="identity"><a href="/" aria-label="Muscle Atlas home"><span className="eyebrow"><i/> EXERCISE EXPLORER</span><h1>Muscle <em>Atlas</em></h1></a><p>Human anatomy in motion</p></header>
  <div className="top-actions"><button className="mobile-toggle" aria-label="Choose exercise" aria-expanded={libraryOpen} onClick={()=>{setLibraryOpen(v=>!v);setInfoOpen(false);}}>{libraryOpen?<X size={19}/>:<Menu size={19}/>}</button><button className="mobile-toggle" aria-label="Movement details" aria-expanded={infoOpen} onClick={()=>{setInfoOpen(v=>!v);setLibraryOpen(false);}}><Info size={19}/></button><Tabs value={goal} onValueChange={v=>setGoal(String(v))} className="goal-tabs"><TabsList aria-label="Training goal"><TabsTrigger value="build">Build muscle</TabsTrigger><TabsTrigger value="lean">Lean up</TabsTrigger></TabsList></Tabs></div>
  <section className="viewport" aria-label="3D exercise viewer">
   <AnatomyScene exercise={exercise} progress={progress} view={view} reset={reset} onReady={setReady}/>
   <div className="view-switch glass" role="group" aria-label="Camera view">{(['front','side','back'] as View[]).map(v=><button key={v} aria-pressed={view===v} onClick={()=>setView(v)} className={view===v?'selected':''}>{v}</button>)}<span/><button aria-label="Reset camera" onClick={()=>{setView('front');setReset(v=>v+1);}}><RotateCcw size={16}/></button></div>
   <p className="orbit-hint">Drag to rotate <span>·</span> Scroll or pinch to zoom</p>
  </section>
  <aside className={'library glass '+(libraryOpen?'mobile-open':'')} aria-label="Exercise library"><div className="panel-heading"><h2>Exercises</h2><span>11 movements</span></div>
   <Tabs value={group} onValueChange={v=>{const e=exercises.find(x=>x.group===v);if(e)choose(e.id);}} className="muscle-tabs"><TabsList aria-label="Muscle group">{groups.map(g=><TabsTrigger value={g} key={g}>{g}</TabsTrigger>)}</TabsList>{groups.map(g=><TabsContent key={g} value={g}>{exercises.filter(e=>e.group===g).map(e=><button aria-pressed={e.id===id} className={'exercise '+(e.id===id?'active':'')} key={e.id} onClick={()=>{choose(e.id);setLibraryOpen(false);}}><span>{e.name}<small>{e.equipment}</small></span>{e.id===id?<Check size={15}/>:<ChevronRight size={15}/>}</button>)}</TabsContent>)}</Tabs>
   <div className="role-key"><span><i/> Primary</span><span><i/> Assisting</span></div>
  </aside>
  <aside className={'details glass '+(infoOpen?'mobile-open':'')} aria-label="Movement details"><span className="eyebrow">{exercise.group} / {exercise.equipment}</span><h2>{exercise.name}</h2><p className="action">{exercise.action}</p>{exercise.group==='Back'&&<p className="schematic-note">Lat surfaces are schematic.</p>}
   <section className="muscle-legend" aria-labelledby="muscle-legend-title"><div className="legend-heading"><h3 id="muscle-legend-title">Muscle legend</h3><span>Color on model</span></div>{exercise.primary.map(m=><div className="legend-row primary" key={'primary-'+m}><i aria-hidden="true"/><div><strong>{m}</strong><p>{describeMuscle(m)}</p></div></div>)}{exercise.secondary.map(m=><div className="legend-row assisting" key={'assisting-'+m}><i aria-hidden="true"/><div><strong>{m}</strong><p>{describeMuscle(m)}</p></div></div>)}</section>
   <details className="disclosure"><summary>Form cues<Plus size={14}/></summary><ol>{exercise.cues.map(cue=><li key={cue}>{cue}</li>)}</ol></details>
   <details className="disclosure"><summary>{goal==='build'?'Building muscle':'Leaning up'}<Plus size={14}/></summary><p>{goal==='build'?'Use a resistance you can control. As training becomes easier, gradually increase the challenge. Target reps control this demo, not a personalized program.':'Strength training supports an active routine. Fat loss depends on overall energy balance; more reps do not target fat in a selected muscle area.'}</p><a href={goal==='build'?'https://www.acefitness.org/resources/everyone/exercise-library/':'https://www.cdc.gov/healthy-weight-growth/physical-activity/index.html'} target="_blank" rel="noreferrer">{goal==='build'?'ACE exercise library':'CDC activity guide'}<ArrowUpRight size={13}/></a></details>
  </aside>
  <section className="bottom-dock glass" aria-label="Exercise playback">
   <div className="dock-title"><div><h2>{exercise.name}</h2><p>{complete?'Set complete':progress===0?'Ready when you are':exercise.phase[phaseIndex]}</p></div><span className="rep-count" aria-label={Math.floor(progress)+' reps completed'}>{String(Math.floor(progress)).padStart(2,'0')}<small> / {reps}</small></span></div>
   <div className="dock-controls"><button className="play-button" disabled={!ready} aria-label={complete?'Replay set':playing?'Pause set':progress>0?'Resume set':'Start set'} onClick={()=>{if(complete)seek(0);setPlaying(v=>!v);}}>{complete?<RotateCcw size={19}/>:playing?<Pause size={19}/>:<Play size={19}/>}</button><Field.Root className="slider-field"><Field.Label className="sr-only">Position in current rep</Field.Label><Slider min={0} max={.999} step={.001} value={[fraction]} disabled={!ready||complete} onValueChange={v=>{setPlaying(false);playingRef.current=false;seek(Math.floor(progress)+(Array.isArray(v)?v[0]:v));}}/></Field.Root><button className="reset-set" aria-label="Reset set" onClick={clear}><RotateCcw size={16}/></button></div>
   <div className="dock-options"><div className="rep-control"><span>Reps</span><div className="stepper"><button aria-label="Decrease reps" disabled={reps<=1} onClick={()=>{clear();setReps(v=>v-1);}}><Minus size={13}/></button><b>{reps}</b><button aria-label="Increase reps" disabled={reps>=30} onClick={()=>{clear();setReps(v=>v+1);}}><Plus size={13}/></button></div></div><div className="speed-control" role="group" aria-label="Playback speed">{[.5,1,1.5].map(s=><button aria-pressed={s===speed} key={s} className={speed===s?'selected':''} onClick={()=>setSpeed(s)}>{s}×</button>)}</div></div><span className="sr-only" aria-live="polite">{complete?reps+' reps completed':''}</span>
  </section>
  <footer><span>BodyParts3D <b>·</b> Educational visualization</span><details className="credits"><summary><Info size={13}/> About this model</summary><div className="about-content glass"><h2>About the model</h2><p>BodyParts3D adult male reference anatomy, © The Database Center for Life Science, <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>. Adapted from <a href="https://github.com/ashemag/human-atlas">Human Atlas</a>.</p><p>The two lat surfaces are schematic additions. Joint motion, muscle thickening and highlights are illustrative, not measured activation or validated biomechanics. Equipment is omitted; pulldown motion is shown without a seated setup.</p><a href="/ATTRIBUTION.md">Full attribution <ArrowUpRight size={13}/></a></div></details></footer>
 </main>;
}
